api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "custom-pricing"
type = "function"
uid = "8549077a-a8d0-17af-6f97-0497ca93c2b4befadff8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
